// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_UDtYGDKkgk-bqwswCI-FGzNB8SQHjJA',
    appId: '1:188501020543:web:55b29dd362f6a3521e944a',
    messagingSenderId: '188501020543',
    projectId: 'simple-painter-a105a',
    authDomain: 'simple-painter-a105a.firebaseapp.com',
    storageBucket: 'simple-painter-a105a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb8T7mzuUGcdWYFHowqJTYh1p-9qW8eco',
    appId: '1:188501020543:android:1ba24033ad34c2231e944a',
    messagingSenderId: '188501020543',
    projectId: 'simple-painter-a105a',
    storageBucket: 'simple-painter-a105a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HQdpDPdIO41RsRvzXSAgrFroI3l_viY',
    appId: '1:188501020543:ios:d88df101845f61021e944a',
    messagingSenderId: '188501020543',
    projectId: 'simple-painter-a105a',
    storageBucket: 'simple-painter-a105a.firebasestorage.app',
    iosBundleId: 'com.example.simplePaint',
  );
}
